# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# What is the value of the first triangle number to have over five hundred divisors?

import time

def triangle_number(num):
	triangle = 0
	for i in range(num):
		triangle += i
	return triangle

def number_divisors(num):
	count = 0
	for i in range(1,(num/2)+1):
		if num % i == 0:
			count += 1
	return count

mark = time.time()
for i in range(0,1000):
	tri = triangle_number(i)
	div = number_divisors(tri)
	if div > 500:
		break
print time.time()-mark