# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fib(num):
	if num == 0:
		return 1
	if num == 1:
		return 1
	return fib(num-1)+fib(num-2)

total = []
for int in range(2,100,3):
	cur = fib(int)
	if cur < 4e6:
		total.append(fib(int))
	else:
		break

print sum(total)
